### ISSUE TITLE
Device Configuration

### ISSUE THREAD

**Issue by kareniel** [vibedrive/api-spec#1]
Dreaming up an example config for devices:

```yaml
devices:
  - 
      name: "Vibedrive Cloud"
      capacity: 1TB
      rules:
        - sync whole collection
        - share object storage
  -
      name: "NAS"
      capacity: 2TB
      rules:
        - sync whole collection
  - 
      name: "Macbook"
      capacity: 500GB
      rules:
        - share object storage
        - sync following playlists:
          - playlist:inbox
          - playlist:current_crate
  - 
      name: "USB C Key A"
      capacity: 64GB
      rules:
        - sync following playlist tag:
          - playlist:gigs
  - 
      name: "USB C Key B"
      capacity: 16GB
      rules:
        - sync following playlists:
          - playlist:current_crate
  - 
      name: "iPhone"
      capacity: 12GB
      rules:
        - sync following playlists:
          - playlist:inbox
          - playlist:current_crate
```
